<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>WinExe</OutputType><TargetFramework>net8.0-windows</TargetFramework><UseWindowsForms>true</UseWindowsForms><EnableWindowsTargeting>true</EnableWindowsTargeting><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup>
  <ItemGroup><ProjectReference Include="../DataAccess/QuanLySinhVien.DataAccess.csproj" /><ProjectReference Include="../Entity/QuanLySinhVien.Entity.csproj" /><ProjectReference Include="../Business/QuanLySinhVien.Business.csproj" /></ItemGroup>
</Project>
